/**
 * Migration 003: System Tables
 * - tenants (Nhà hàng)
 * - platform_users (Super Admin)
 * - app_settings (Cấu hình riêng từng tenant)
 */

export async function up(knex) {
    // 1. Tenants table
    await knex.raw(`
    CREATE TABLE tenants (
      id UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
      name VARCHAR(100) NOT NULL,
      slug VARCHAR(50) NOT NULL UNIQUE,
      email VARCHAR(100) NOT NULL,
      status VARCHAR(20) DEFAULT 'active',
      logo_url TEXT,
      address TEXT,
      phone VARCHAR(50),
      tax_rate NUMERIC(5, 2) DEFAULT 5.00,
      service_charge NUMERIC(5, 2) DEFAULT 0.00,
      discount_rules JSONB DEFAULT '[]'::jsonb,
      qr_payment TEXT,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );
  `);

    // 2. Platform Users table (Super Admin)
    await knex.raw(`
    CREATE TABLE platform_users (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      email VARCHAR(100) NOT NULL UNIQUE,
      password_hash VARCHAR(255) NOT NULL,
      role VARCHAR(20) DEFAULT 'super_admin',
      name VARCHAR(100),
      refresh_token_hash TEXT,
      refresh_token_expires TIMESTAMP WITH TIME ZONE,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
      updated_at TIMESTAMP WITHOUT TIME ZONE
    );
  `);

    // 3. App Settings table
    await knex.raw(`
    CREATE TABLE app_settings (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
      key VARCHAR(50) NOT NULL,
      value TEXT NOT NULL,
      value_type VARCHAR(20) NOT NULL,
      category VARCHAR(50) NOT NULL,
      description TEXT,
      is_system BOOLEAN NOT NULL DEFAULT false,
      UNIQUE(tenant_id, key)
    );
  `);
}

export async function down(knex) {
    await knex.raw(`DROP TABLE IF EXISTS app_settings;`);
    await knex.raw(`DROP TABLE IF EXISTS platform_users;`);
    await knex.raw(`DROP TABLE IF EXISTS tenants;`);
}
