/**
 * Migration 004: Resource Tables
 * - users (Nhân viên)
 * - customers (Khách hàng)
 * - categories (Danh mục món)
 * - dishes (Món ăn)
 * - dish_ratings
 * - menu_item_photos
 * - modifier_groups
 * - modifier_options
 * - menu_item_modifier_groups
 */

export async function up(knex) {
    // 1. Users table (Staff)
    await knex.raw(`
    CREATE TABLE users (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
      email VARCHAR(100) NOT NULL,
      password_hash VARCHAR(255) NOT NULL,
      full_name VARCHAR(100),
      role VARCHAR(20) NOT NULL DEFAULT 'waiter',
      is_active BOOLEAN DEFAULT true,
      phone_number TEXT,
      date_of_birth DATE,
      hometown TEXT,
      avatar_url TEXT,
      avatar_type VARCHAR(20) DEFAULT 'default',
      refresh_token_hash TEXT,
      refresh_token_expires TIMESTAMP WITH TIME ZONE,
      CONSTRAINT users_tenant_email_unique UNIQUE (tenant_id, email)
    );
  `);

    // 2. Customers table
    await knex.raw(`
    CREATE TABLE customers (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
      full_name VARCHAR(100),
      phone_number VARCHAR(15),
      email TEXT,
      password TEXT,
      loyalty_points INTEGER DEFAULT 0,
      is_active BOOLEAN DEFAULT true,
      google_id TEXT,
      avatar TEXT,
      CONSTRAINT customers_tenant_phone_unique UNIQUE (tenant_id, phone_number)
    );
  `);

    // 3. Categories table
    await knex.raw(`
    CREATE TABLE categories (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
      name VARCHAR(100) NOT NULL,
      display_order INTEGER DEFAULT 0,
      is_active BOOLEAN DEFAULT true,
      url_icon TEXT,
      description TEXT,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
      UNIQUE (tenant_id, name)
    );
  `);

    // 4. Dishes table
    await knex.raw(`
    CREATE TABLE dishes (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
      category_id INTEGER REFERENCES categories(id) ON DELETE SET NULL,
      name VARCHAR(150) NOT NULL,
      description TEXT,
      price NUMERIC(12, 2) NOT NULL,
      image_url TEXT,
      is_available BOOLEAN DEFAULT true,
      status dish_status DEFAULT 'Available',
      prep_time_minutes INTEGER DEFAULT 0 CHECK (prep_time_minutes >= 0 AND prep_time_minutes <= 240),
      is_recommended BOOLEAN DEFAULT false,
      order_count BIGINT DEFAULT 0,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );
  `);

    // 5. Dish Ratings table
    await knex.raw(`
    CREATE TABLE dish_ratings (
      id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      dish_id INTEGER NOT NULL REFERENCES dishes(id) ON DELETE CASCADE,
      total_reviews BIGINT DEFAULT 0,
      average_rating REAL DEFAULT 0,
      rating_1 SMALLINT DEFAULT 0,
      rating_2 SMALLINT DEFAULT 0,
      rating_3 SMALLINT DEFAULT 0,
      rating_4 SMALLINT DEFAULT 0,
      rating_5 SMALLINT DEFAULT 0
    );
  `);

    // 6. Menu Item Photos table
    await knex.raw(`
    CREATE TABLE menu_item_photos (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      dish_id INTEGER REFERENCES dishes(id) ON DELETE CASCADE,
      url TEXT NOT NULL,
      is_primary BOOLEAN DEFAULT FALSE,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );
  `);

    // 7. Modifier Groups table
    await knex.raw(`
    CREATE TABLE modifier_groups (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
      name VARCHAR(80) NOT NULL,
      selection_type VARCHAR(20) NOT NULL CHECK (selection_type IN ('single', 'multiple')),
      is_required BOOLEAN DEFAULT FALSE,
      min_selections INTEGER DEFAULT 0,
      max_selections INTEGER DEFAULT 0,
      display_order INTEGER DEFAULT 0,
      is_active BOOLEAN DEFAULT TRUE,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );
  `);

    // 8. Modifier Options table
    await knex.raw(`
    CREATE TABLE modifier_options (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      group_id INTEGER NOT NULL REFERENCES modifier_groups(id) ON DELETE CASCADE,
      name VARCHAR(80) NOT NULL,
      price_adjustment NUMERIC(12,2) DEFAULT 0 CHECK (price_adjustment >= 0),
      is_active BOOLEAN DEFAULT TRUE,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );
  `);

    // 9. Menu Item Modifier Groups (Junction table)
    await knex.raw(`
    CREATE TABLE menu_item_modifier_groups (
      dish_id INTEGER NOT NULL REFERENCES dishes(id) ON DELETE CASCADE,
      group_id INTEGER NOT NULL REFERENCES modifier_groups(id) ON DELETE CASCADE,
      PRIMARY KEY (dish_id, group_id)
    );
  `);
}

export async function down(knex) {
    await knex.raw(`DROP TABLE IF EXISTS menu_item_modifier_groups;`);
    await knex.raw(`DROP TABLE IF EXISTS modifier_options;`);
    await knex.raw(`DROP TABLE IF EXISTS modifier_groups;`);
    await knex.raw(`DROP TABLE IF EXISTS menu_item_photos;`);
    await knex.raw(`DROP TABLE IF EXISTS dish_ratings;`);
    await knex.raw(`DROP TABLE IF EXISTS dishes;`);
    await knex.raw(`DROP TABLE IF EXISTS categories;`);
    await knex.raw(`DROP TABLE IF EXISTS customers;`);
    await knex.raw(`DROP TABLE IF EXISTS users;`);
}
