/**
 * Migration 005: Business Tables
 * - tables (Bàn ăn)
 * - orders (Đơn hàng)
 * - order_details (Chi tiết đơn hàng)
 * - order_item_modifiers
 * - payments (Thanh toán)
 * - reviews (Đánh giá)
 */

export async function up(knex) {
    // 1. Tables (Bàn ăn)
    // Note: current_order_id FK sẽ được thêm ở migration 006
    await knex.raw(`
    CREATE TABLE tables (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
      table_number VARCHAR(20) NOT NULL,
      capacity INTEGER DEFAULT 4 CHECK (capacity > 0 AND capacity <= 20),
      location table_location DEFAULT 'Indoor',
      status table_status DEFAULT 'Available',
      qr_token VARCHAR(500),
      qr_token_created_at TIMESTAMP,
      current_order_id BIGINT,
      description VARCHAR(80),
      is_vip BOOLEAN NOT NULL DEFAULT false,
      created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
      updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
      CONSTRAINT tables_tenant_number_unique UNIQUE (tenant_id, table_number)
    );
  `);

    // 2. Orders table
    await knex.raw(`
    CREATE TABLE orders (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
      table_id INTEGER REFERENCES tables(id) ON DELETE SET NULL,
      customer_id INTEGER REFERENCES customers(id) ON DELETE SET NULL,
      waiter_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
      status order_status DEFAULT 'Unsubmit',
      total_amount NUMERIC(12, 2) DEFAULT 0,
      prep_time_order INTEGER DEFAULT 0,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
      completed_at TIMESTAMP WITH TIME ZONE
    );
  `);

    // 3. Order Details table
    await knex.raw(`
    CREATE TABLE order_details (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
      order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
      dish_id INTEGER REFERENCES dishes(id) ON DELETE SET NULL,
      quantity INTEGER NOT NULL CHECK (quantity > 0),
      unit_price NUMERIC(12, 2) NOT NULL,
      total_price NUMERIC(12, 2) GENERATED ALWAYS AS (quantity * unit_price) STORED,
      note VARCHAR(255),
      status item_status DEFAULT 'Pending'
    );
  `);

    // 4. Order Item Modifiers table
    await knex.raw(`
    CREATE TABLE order_item_modifiers (
      id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      order_detail_id BIGINT NOT NULL REFERENCES order_details(id) ON DELETE CASCADE,
      modifier_option_id INTEGER REFERENCES modifier_options(id) ON DELETE SET NULL,
      option_name TEXT,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );
  `);

    // 5. Payments table
    await knex.raw(`
    CREATE TABLE payments (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
      order_id BIGINT UNIQUE REFERENCES orders(id) ON DELETE CASCADE,
      amount NUMERIC(12, 2) NOT NULL,
      payment_method payment_method_enum DEFAULT 'Cash',
      payment_status VARCHAR(20) DEFAULT 'pending',
      transaction_id VARCHAR(100),
      paid_at TIMESTAMP WITH TIME ZONE,
      subtotal NUMERIC DEFAULT 0,
      tax_rate NUMERIC DEFAULT 0,
      tax_amount NUMERIC DEFAULT 0,
      service_charge_rate NUMERIC DEFAULT 0,
      service_charge_amount NUMERIC DEFAULT 0,
      discount_percent NUMERIC DEFAULT 0,
      discount_amount NUMERIC DEFAULT 0
    );
  `);

    // 6. Reviews table
    await knex.raw(`
    CREATE TABLE reviews (
      id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
      dish_id INTEGER REFERENCES dishes(id) ON DELETE SET NULL,
      order_id BIGINT REFERENCES orders(id) ON DELETE SET NULL,
      rating SMALLINT CHECK (rating >= 1 AND rating <= 5),
      comment TEXT,
      created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
    );
  `);
}

export async function down(knex) {
    await knex.raw(`DROP TABLE IF EXISTS reviews;`);
    await knex.raw(`DROP TABLE IF EXISTS payments;`);
    await knex.raw(`DROP TABLE IF EXISTS order_item_modifiers;`);
    await knex.raw(`DROP TABLE IF EXISTS order_details;`);
    await knex.raw(`DROP TABLE IF EXISTS orders;`);
    await knex.raw(`DROP TABLE IF EXISTS tables;`);
}
