-- ================================================================
-- PHẦN 0: EXTENSIONS & HELPER FUNCTIONS
-- ================================================================

-- Kích hoạt extension cần thiết
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Hàm tạo UUIDv7 chuẩn (Giữ lại bản tối ưu nhất)
CREATE OR REPLACE FUNCTION uuid_generate_v7()
RETURNS uuid
LANGUAGE plpgsql
VOLATILE
AS $$
DECLARE
  ts_bytes BYTEA;
  uuid_bytes BYTEA;
BEGIN
  -- 48-bit Unix timestamp (ms)
  ts_bytes := decode(
    lpad(
      to_hex(floor(extract(epoch FROM clock_timestamp()) * 1000)::bigint),
      12,
      '0'
    ),
    'hex'
  );
  -- Random base
  uuid_bytes := gen_random_bytes(16);
  -- Inject timestamp
  uuid_bytes := overlay(uuid_bytes placing ts_bytes from 1 for 6);
  -- Version = 7
  uuid_bytes := set_byte(uuid_bytes, 6, (get_byte(uuid_bytes, 6) & 15) | 112);
  -- Variant = RFC 4122
  uuid_bytes := set_byte(uuid_bytes, 8, (get_byte(uuid_bytes, 8) & 63) | 128);
  
  RETURN encode(uuid_bytes, 'hex')::uuid;
END;
$$;

-- ================================================================
-- PHẦN 1: ENUMS (Định nghĩa kiểu dữ liệu)
-- ================================================================

DO $$ BEGIN
    CREATE TYPE dish_status AS ENUM ('Available', 'Out_of_Stock', 'Hidden');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE item_status AS ENUM ('Pending', 'Ready', 'Served', 'Cancelled');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE table_location AS ENUM ('Indoor', 'Outdoor', 'Patio', 'VIP_Room');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE table_status AS ENUM ('Active', 'Inactive', 'Available', 'Occupied');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE order_status AS ENUM ('Unsubmit', 'Approved', 'Pending', 'Completed', 'Served', 'Paid', 'Cancelled');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE payment_method_enum AS ENUM ('Cash', 'Credit_Card', 'Bank_Transfer', 'QR_Code');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- ================================================================
-- PHẦN 2: SYSTEM & TENANT TABLES
-- ================================================================

-- 1. Tenants (Nhà hàng)
CREATE TABLE public.tenants (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL,
    status VARCHAR(20) DEFAULT 'active',
    logo_url TEXT,
    address TEXT,
    phone VARCHAR(50),
    tax_rate NUMERIC(5, 2) DEFAULT 5.00,
    service_charge NUMERIC(5, 2) DEFAULT 0.00,
    discount_rules JSONB DEFAULT '[]'::jsonb,
    qr_payment TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Platform Users (Super Admin quản lý hệ thống)
CREATE TABLE public.platform_users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) DEFAULT 'super_admin',
    name VARCHAR(100),
    refresh_token_hash TEXT,
    refresh_token_expires TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE
);

-- 3. App Settings (Cấu hình riêng cho từng Tenant)
CREATE TABLE public.app_settings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    key VARCHAR(50) NOT NULL,
    value TEXT NOT NULL,
    value_type VARCHAR(20) NOT NULL,
    category VARCHAR(50) NOT NULL,
    description TEXT,
    is_system BOOLEAN NOT NULL DEFAULT false,
    UNIQUE(tenant_id, key) -- Đảm bảo key là duy nhất trong phạm vi 1 tenant
);

-- ================================================================
-- PHẦN 3: RESOURCES & OPERATIONS
-- ================================================================

-- 4. Users (Nhân viên nhà hàng)
CREATE TABLE public.users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    email VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(100),
    role VARCHAR(20) NOT NULL DEFAULT 'waiter',
    is_active BOOLEAN DEFAULT true,
    phone_number TEXT,
    date_of_birth DATE,
    hometown TEXT,
    avatar_url TEXT,
    avatar_type VARCHAR(20) DEFAULT 'default',
    refresh_token_hash TEXT,
    refresh_token_expires TIMESTAMP WITH TIME ZONE,
    
    -- QUAN TRỌNG: Email phải duy nhất trong 1 tenant, nhưng có thể trùng ở tenant khác
    CONSTRAINT users_tenant_email_unique UNIQUE (tenant_id, email)
);

-- 5. Customers (Khách hàng)
CREATE TABLE public.customers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    full_name VARCHAR(100),
    phone_number VARCHAR(15),
    email TEXT,
    password TEXT,
    loyalty_points INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    google_id TEXT,
    avatar TEXT,
    
    -- Một khách hàng (SĐT) là duy nhất trong 1 nhà hàng
    CONSTRAINT customers_tenant_phone_unique UNIQUE (tenant_id, phone_number)
);

-- 6. Categories (Danh mục món)
CREATE TABLE public.categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    display_order INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    url_icon TEXT,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE (tenant_id, name)
);

-- 7. Dishes (Món ăn)
CREATE TABLE public.dishes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    category_id INTEGER REFERENCES public.categories(id) ON DELETE SET NULL,
    name VARCHAR(150) NOT NULL,
    description TEXT,
    price NUMERIC(12, 2) NOT NULL,
    image_url TEXT,
    is_available BOOLEAN DEFAULT true,
    status dish_status DEFAULT 'Available',
    prep_time_minutes INTEGER DEFAULT 0 CHECK (prep_time_minutes >= 0 AND prep_time_minutes <= 240),
    is_recommended BOOLEAN DEFAULT false,
    order_count BIGINT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 8. Dish Ratings & Photos
CREATE TABLE public.dish_ratings (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    dish_id INTEGER NOT NULL REFERENCES public.dishes(id) ON DELETE CASCADE,
    total_reviews BIGINT DEFAULT 0,
    average_rating REAL DEFAULT 0,
    rating_1 SMALLINT DEFAULT 0,
    rating_2 SMALLINT DEFAULT 0,
    rating_3 SMALLINT DEFAULT 0,
    rating_4 SMALLINT DEFAULT 0,
    rating_5 SMALLINT DEFAULT 0
);

CREATE TABLE public.menu_item_photos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dish_id INTEGER REFERENCES public.dishes(id) ON DELETE CASCADE,
    url TEXT NOT NULL,
    is_primary BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 9. Modifiers (Topping/Tùy chọn)
CREATE TABLE public.modifier_groups (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    name VARCHAR(80) NOT NULL,
    selection_type VARCHAR(20) NOT NULL CHECK (selection_type IN ('single', 'multiple')),
    is_required BOOLEAN DEFAULT FALSE,
    min_selections INTEGER DEFAULT 0,
    max_selections INTEGER DEFAULT 0,
    display_order INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT True,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE public.modifier_options (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id INTEGER NOT NULL REFERENCES public.modifier_groups(id) ON DELETE CASCADE,
    name VARCHAR(80) NOT NULL,
    price_adjustment NUMERIC(12,2) DEFAULT 0 CHECK (price_adjustment >= 0),
    is_active BOOLEAN DEFAULT True,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE public.menu_item_modifier_groups (
    dish_id INTEGER NOT NULL REFERENCES public.dishes(id) ON DELETE CASCADE,
    group_id INTEGER NOT NULL REFERENCES public.modifier_groups(id) ON DELETE CASCADE,
    PRIMARY KEY (dish_id, group_id)
);

-- ================================================================
-- PHẦN 4: CORE BUSINESS (TABLES & ORDERS)
-- ================================================================

-- 10. Tables (Bàn ăn)
-- Lưu ý: current_order_id sẽ được trỏ FK sau để tránh Circular Dependency
CREATE TABLE public.tables (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    table_number VARCHAR(20) NOT NULL, 
    capacity INTEGER DEFAULT 4 CHECK (capacity > 0 AND capacity <= 20),
    location table_location DEFAULT 'Indoor',
    status table_status DEFAULT 'Available',
    qr_token VARCHAR(500),
    qr_token_created_at TIMESTAMP,
    current_order_id BIGINT, -- Sẽ add FK sau
    description VARCHAR(80),
    is_vip BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    
    -- QUAN TRỌNG: Tên bàn chỉ duy nhất trong phạm vi 1 tenant
    CONSTRAINT tables_tenant_number_unique UNIQUE (tenant_id, table_number)
);

-- 11. Orders (Đơn hàng)
CREATE TABLE public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    table_id INTEGER REFERENCES public.tables(id) ON DELETE SET NULL,
    customer_id INTEGER REFERENCES public.customers(id) ON DELETE SET NULL,
    waiter_id INTEGER REFERENCES public.users(id) ON DELETE SET NULL,
    
    status order_status DEFAULT 'Unsubmit',
    total_amount NUMERIC(12, 2) DEFAULT 0,
    prep_time_order INTEGER DEFAULT 0,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    completed_at TIMESTAMP WITH TIME ZONE
);

-- 12. Order Details (Chi tiết đơn hàng)
CREATE TABLE public.order_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    order_id BIGINT NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    dish_id INTEGER REFERENCES public.dishes(id) ON DELETE SET NULL,
    
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price NUMERIC(12, 2) NOT NULL,
    total_price NUMERIC(12, 2) GENERATED ALWAYS AS (quantity * unit_price) STORED, -- Tự động tính
    note VARCHAR(255),
    status item_status DEFAULT 'Pending'
);

CREATE TABLE public.order_item_modifiers (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    order_detail_id BIGINT NOT NULL REFERENCES public.order_details(id) ON DELETE CASCADE,
    modifier_option_id INTEGER REFERENCES public.modifier_options(id) ON DELETE SET NULL,
    option_name TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 13. Payments (Thanh toán)
CREATE TABLE public.payments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    order_id BIGINT UNIQUE REFERENCES public.orders(id) ON DELETE CASCADE,
    
    amount NUMERIC(12, 2) NOT NULL,
    payment_method payment_method_enum DEFAULT 'Cash',
    payment_status VARCHAR(20) DEFAULT 'pending',
    transaction_id VARCHAR(100),
    paid_at TIMESTAMP WITH TIME ZONE,
    
    subtotal NUMERIC DEFAULT 0,
    tax_rate NUMERIC DEFAULT 0,
    tax_amount NUMERIC DEFAULT 0,
    service_charge_rate NUMERIC DEFAULT 0,
    service_charge_amount NUMERIC DEFAULT 0,
    discount_percent NUMERIC DEFAULT 0,
    discount_amount NUMERIC DEFAULT 0
);

-- 14. Reviews (Đánh giá)
CREATE TABLE public.reviews (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    customer_id INTEGER NOT NULL REFERENCES public.customers(id) ON DELETE CASCADE,
    dish_id INTEGER REFERENCES public.dishes(id) ON DELETE SET NULL,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE SET NULL,
    rating SMALLINT CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

-- ================================================================
-- PHẦN 5: CONSTRAINTS & INDEXES (Tối ưu)
-- ================================================================

-- 5.1 Xử lý mối quan hệ vòng giữa Tables và Orders
-- (Giờ bảng orders đã tồn tại, ta mới trỏ khóa ngoại từ tables sang)
ALTER TABLE public.tables
ADD CONSTRAINT fk_tables_current_order
FOREIGN KEY (current_order_id) REFERENCES public.orders(id) ON DELETE SET NULL;

-- 5.2 Indexes cho Tenant ID (BẮT BUỘC để tối ưu hiệu năng Multi-tenant)
CREATE INDEX idx_users_tenant ON public.users(tenant_id);
CREATE INDEX idx_tables_tenant ON public.tables(tenant_id);
CREATE INDEX idx_categories_tenant ON public.categories(tenant_id);
CREATE INDEX idx_dishes_tenant ON public.dishes(tenant_id);
CREATE INDEX idx_customers_tenant ON public.customers(tenant_id);
CREATE INDEX idx_orders_tenant ON public.orders(tenant_id);
CREATE INDEX idx_order_details_tenant ON public.order_details(tenant_id);
CREATE INDEX idx_payments_tenant ON public.payments(tenant_id);

-- 5.3 Indexes cho các khóa ngoại phổ biến
CREATE INDEX idx_dishes_category ON public.dishes(category_id);
CREATE INDEX idx_orders_customer ON public.orders(customer_id);
CREATE INDEX idx_orders_table ON public.orders(table_id);
CREATE INDEX idx_order_details_order ON public.order_details(order_id);